import { debug, info, warning } from '@actions/core'
import { context, getOctokit } from '@actions/github'

// GitHub caps issue/PR comment bodies at 65536 characters.
const MAX_COMMENT_LENGTH = 65536

// reportx's own severity order, worst first.
// See https://github.com/cerberauth/reportx/blob/main/finding.go
const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low', 'info']

interface ReportxFinding {
  title: string
  severity: string
  url?: string
}

interface ReportxReport {
  metadata: {
    total: number
    by_severity?: Record<string, number>
  }
  findings: ReportxFinding[]
}

export interface BuildCommentBodyOptions {
  // Name of the tool that produced the report, e.g. "jwtop". Used in the
  // comment heading and to scope the marker used to find/update this
  // comment across runs.
  toolName: string
  // Docs URL linked from the comment footer.
  docsUrl: string
}

export function isPullRequestEvent(): boolean {
  return (
    (context.eventName === 'pull_request' ||
      context.eventName === 'pull_request_target') &&
    context.payload.pull_request != null
  )
}

// The workflow run this action is executing in, used as a fallback link
// when the full findings summary doesn't fit in a PR comment.
export function workflowRunUrl(): string {
  const { owner, repo } = context.repo
  return `${context.serverUrl}/${owner}/${repo}/actions/runs/${context.runId}`
}

function commentMarker(toolName: string): string {
  return `<!-- cerberauth/${toolName} -->`
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function severityCounts(report: ReportxReport): [string, number][] {
  const counts =
    report.metadata.by_severity ??
    report.findings.reduce<Record<string, number>>((acc, f) => {
      acc[f.severity] = (acc[f.severity] ?? 0) + 1
      return acc
    }, {})

  return SEVERITY_ORDER.filter((severity) => counts[severity]).map(
    (severity): [string, number] => [severity, counts[severity]]
  )
}

function renderFindingsList(findings: ReportxFinding[]): string {
  if (findings.length === 0) {
    return 'No findings.'
  }

  const bySeverity = [...findings].sort(
    (a, b) =>
      SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity)
  )

  return bySeverity
    .map((f) => {
      const severity = `\`${capitalize(f.severity)}\``
      return f.url
        ? `- **${f.title}** (${severity}) — ${f.url}`
        : `- **${f.title}** (${severity})`
    })
    .join('\n')
}

function renderSeverityTable(report: ReportxReport): string {
  const counts = severityCounts(report)
  if (counts.length === 0) {
    return 'No findings.'
  }

  const rows = counts
    .map(([severity, count]) => `| ${capitalize(severity)} | ${count} |`)
    .join('\n')
  return `| Severity | Count |\n|----------|-------|\n${rows}`
}

function footer(options: BuildCommentBodyOptions): string {
  return `\n\n---\nGenerated by [${options.toolName}](${options.docsUrl}).`
}

// Builds a PR comment body out of a reportx JSON report: a summary listing
// every finding with its severity and URL. When that summary would be too
// large for a GitHub comment, falls back to a per-severity finding count
// plus a link to the workflow run, where the full report is still available
// (as an artifact, in the logs, ...).
export function buildCommentBody(
  reportJson: string,
  options: BuildCommentBodyOptions
): string {
  const report = JSON.parse(reportJson) as ReportxReport
  const marker = commentMarker(options.toolName)

  const summary = `## ${options.toolName} scan results\n\n${renderFindingsList(report.findings ?? [])}`
  const full = `${marker}\n${summary}${footer(options)}`
  if (full.length <= MAX_COMMENT_LENGTH) {
    return full
  }

  const table = `## ${options.toolName} scan results\n\n${renderSeverityTable(report)}\n\nThe full findings summary is too large for a PR comment — see the [workflow run](${workflowRunUrl()}) for details.`
  return `${marker}\n${table}${footer(options)}`
}

// Creates or updates the PR comment carrying the scan results. Any failure
// (most commonly a token without pull-requests/issues write access, e.g. on
// forked-repo pull requests) is logged as a warning rather than failing the
// action, since commenting is a best-effort convenience on top of the scan.
// The comment to update, if any, is identified by the marker on the first
// line of `body` (as produced by buildCommentBody), so different tools
// commenting on the same PR don't clobber each other's comments.
export async function postScanComment(
  token: string,
  body: string
): Promise<void> {
  const pullRequest = context.payload.pull_request
  if (!pullRequest) {
    debug('Not running for a pull request, skipping comment')
    return
  }

  const { owner, repo } = context.repo
  const issue_number = pullRequest.number
  const marker = body.split('\n')[0]

  try {
    const octokit = getOctokit(token)

    const comments = await octokit.rest.issues.listComments({
      owner,
      repo,
      issue_number
    })
    const existing = comments.data.find((c) => c.body?.startsWith(marker))

    if (existing) {
      await octokit.rest.issues.updateComment({
        owner,
        repo,
        comment_id: existing.id,
        body
      })
      info(`Updated scan results comment on PR #${issue_number}`)
    } else {
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number,
        body
      })
      info(`Created scan results comment on PR #${issue_number}`)
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    warning(
      `Skipping PR comment (does the token have pull-requests: write permission?): ${message}`
    )
  }
}
