/**
 * Unit tests for src/comment.ts
 */
import { jest } from '@jest/globals'
import * as core from '../__fixtures__/core.js'
import * as githubModule from '../__fixtures__/github.js'

jest.unstable_mockModule('@actions/core', () => core)
jest.unstable_mockModule('@actions/github', () => githubModule)

const {
  buildCommentBody,
  isPullRequestEvent,
  postScanComment,
  workflowRunUrl
} = await import('../src/comment.js')

const TOOL_OPTIONS = {
  toolName: 'example-tool',
  docsUrl: 'https://www.cerberauth.com/docs/example-tool/'
}

const listComments = jest.fn()
const createComment = jest.fn()
const updateComment = jest.fn()

function reportJson(
  findings: {
    title: string
    severity: string
    url?: string
  }[]
): string {
  const bySeverity: Record<string, number> = {}
  for (const f of findings) {
    bySeverity[f.severity] = (bySeverity[f.severity] ?? 0) + 1
  }
  return JSON.stringify({
    metadata: { total: findings.length, by_severity: bySeverity },
    findings
  })
}

describe('comment.ts', () => {
  beforeEach(() => {
    jest.resetAllMocks()

    githubModule.context.eventName = 'push'
    githubModule.context.payload = {}
    githubModule.context.serverUrl = 'https://github.com'
    githubModule.context.runId = 123456

    listComments.mockResolvedValue({ data: [] })
    githubModule.getOctokit.mockReturnValue({
      rest: {
        issues: { listComments, createComment, updateComment }
      }
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any)
  })

  describe('isPullRequestEvent', () => {
    it('is false for non pull request events', () => {
      githubModule.context.eventName = 'push'
      expect(isPullRequestEvent()).toBe(false)
    })

    it('is true for pull_request events with a pull_request payload', () => {
      githubModule.context.eventName = 'pull_request'
      githubModule.context.payload = { pull_request: { number: 42 } }
      expect(isPullRequestEvent()).toBe(true)
    })

    it('is true for pull_request_target events with a pull_request payload', () => {
      githubModule.context.eventName = 'pull_request_target'
      githubModule.context.payload = { pull_request: { number: 42 } }
      expect(isPullRequestEvent()).toBe(true)
    })

    it('is false for pull_request events without a pull_request payload', () => {
      githubModule.context.eventName = 'pull_request'
      githubModule.context.payload = {}
      expect(isPullRequestEvent()).toBe(false)
    })
  })

  describe('workflowRunUrl', () => {
    it('builds a link to the current workflow run', () => {
      expect(workflowRunUrl()).toBe(
        'https://github.com/cerberauth/example-action/actions/runs/123456'
      )
    })
  })

  describe('buildCommentBody', () => {
    it('lists each finding with its severity and URL', () => {
      const body = buildCommentBody(
        reportJson([
          {
            title: 'Blank Secret',
            severity: 'critical',
            url: 'https://www.cerberauth.com/docs/example-tool/blank-secret/'
          },
          { title: 'Algorithm None', severity: 'high' }
        ]),
        TOOL_OPTIONS
      )

      expect(body).toContain('<!-- cerberauth/example-tool -->')
      expect(body).toContain('## example-tool scan results')
      expect(body).toContain(
        '- **Blank Secret** (`Critical`) — https://www.cerberauth.com/docs/example-tool/blank-secret/'
      )
      expect(body).toContain('- **Algorithm None** (`High`)')
    })

    it('says so when there are no findings', () => {
      const body = buildCommentBody(reportJson([]), TOOL_OPTIONS)
      expect(body).toContain('No findings.')
    })

    it('links to the docs URL with the tool name', () => {
      const body = buildCommentBody(reportJson([]), TOOL_OPTIONS)
      expect(body).toContain(
        'Generated by [example-tool](https://www.cerberauth.com/docs/example-tool/).'
      )
    })

    it('falls back to a severity count table and the workflow run link when too large', () => {
      const findings = Array.from({ length: 2000 }, (_, i) => ({
        title: `Finding ${i}`,
        severity: 'medium',
        url: `https://www.cerberauth.com/docs/example-tool/finding-${i}/`
      }))

      const body = buildCommentBody(reportJson(findings), TOOL_OPTIONS)

      expect(body.length).toBeLessThanOrEqual(65536)
      expect(body).toContain('| Severity | Count |')
      expect(body).toContain('| Medium | 2000 |')
      expect(body).not.toContain('Finding 0')
      expect(body).toContain(
        'https://github.com/cerberauth/example-action/actions/runs/123456'
      )
    })
  })

  describe('postScanComment', () => {
    it('does nothing when there is no pull request in the payload', async () => {
      githubModule.context.payload = {}

      await postScanComment('token', 'body')

      expect(githubModule.getOctokit).not.toHaveBeenCalled()
    })

    it('creates a new comment when none exists yet', async () => {
      githubModule.context.payload = { pull_request: { number: 7 } }

      await postScanComment('token', 'body')

      expect(createComment).toHaveBeenCalledWith(
        expect.objectContaining({
          owner: 'cerberauth',
          repo: 'example-action',
          issue_number: 7,
          body: 'body'
        })
      )
      expect(updateComment).not.toHaveBeenCalled()
    })

    it('updates the existing comment carrying the same marker', async () => {
      githubModule.context.payload = { pull_request: { number: 7 } }
      listComments.mockResolvedValue({
        data: [
          { id: 1, body: 'unrelated comment' },
          { id: 2, body: '<!-- cerberauth/example-tool -->\nold results' }
        ]
      })

      await postScanComment('token', '<!-- cerberauth/example-tool -->\nnew')

      expect(updateComment).toHaveBeenCalledWith(
        expect.objectContaining({ comment_id: 2 })
      )
      expect(createComment).not.toHaveBeenCalled()
    })

    it('does not match a comment carrying a different tool marker', async () => {
      githubModule.context.payload = { pull_request: { number: 7 } }
      listComments.mockResolvedValue({
        data: [{ id: 2, body: '<!-- cerberauth/other-tool -->\nold results' }]
      })

      await postScanComment('token', '<!-- cerberauth/example-tool -->\nnew')

      expect(createComment).toHaveBeenCalled()
      expect(updateComment).not.toHaveBeenCalled()
    })

    it('warns instead of throwing when the API call fails', async () => {
      githubModule.context.payload = { pull_request: { number: 7 } }
      listComments.mockRejectedValue(new Error('Resource not accessible'))

      await expect(postScanComment('token', 'body')).resolves.not.toThrow()

      expect(core.warning).toHaveBeenCalledWith(
        expect.stringContaining('Resource not accessible')
      )
    })
  })
})
